[2021-12-27 22:15:16,837] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: mwaa-sm-customer-churn-dag.process manual__2021-12-28T06:15:08.082341+00:00 [queued]>
[2021-12-27 22:15:16,845] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: mwaa-sm-customer-churn-dag.process manual__2021-12-28T06:15:08.082341+00:00 [queued]>
[2021-12-27 22:15:16,845] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-27 22:15:16,845] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-27 22:15:16,845] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-27 22:15:16,854] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): process> on 2021-12-28 06:15:08.082341+00:00
[2021-12-27 22:15:16,857] {standard_task_runner.py:52} INFO - Started process 37535 to run task
[2021-12-27 22:15:16,864] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'mwaa-sm-customer-churn-dag', 'process', 'manual__2021-12-28T06:15:08.082341+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/mwaa-customer-churn-dag.py', '--cfg-path', '/var/folders/m8/kcmtvg3x5639v8tv9jcxd6700000gn/T/tmpczpfim_g', '--error-file', '/var/folders/m8/kcmtvg3x5639v8tv9jcxd6700000gn/T/tmpa0_vg6mc']
[2021-12-27 22:15:16,865] {standard_task_runner.py:77} INFO - Job 67: Subtask process
[2021-12-27 22:15:16,905] {logging_mixin.py:109} INFO - Running <TaskInstance: mwaa-sm-customer-churn-dag.process manual__2021-12-28T06:15:08.082341+00:00 [running]> on host Shimings-MacBook-Air.local
[2021-12-27 22:15:16,944] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=mwaa-sm-customer-churn-dag
AIRFLOW_CTX_TASK_ID=process
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T06:15:08.082341+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-28T06:15:08.082341+00:00
[2021-12-27 22:15:17,397] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/shimingr/mlops/airflow/dags/mwaa-customer-churn-dag.py", line 87, in preprocess_glue
    glue_client.job_completion(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/botocore/client.py", line 643, in __getattr__
    raise AttributeError(
AttributeError: 'Glue' object has no attribute 'job_completion'
[2021-12-27 22:15:17,418] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=mwaa-sm-customer-churn-dag, task_id=process, execution_date=20211228T061508, start_date=20211228T061516, end_date=20211228T061517
[2021-12-27 22:15:17,432] {standard_task_runner.py:88} ERROR - Failed to execute job 67 for task process
Traceback (most recent call last):
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/shimingr/mlops/airflow/dags/mwaa-customer-churn-dag.py", line 87, in preprocess_glue
    glue_client.job_completion(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/botocore/client.py", line 643, in __getattr__
    raise AttributeError(
AttributeError: 'Glue' object has no attribute 'job_completion'
[2021-12-27 22:15:17,479] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-27 22:15:17,565] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
