[2021-11-17 23:15:38,499] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: mwaa-sm-customer-churn-dag.train manual__2021-11-18T07:15:24.616940+00:00 [queued]>
[2021-11-17 23:15:38,506] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: mwaa-sm-customer-churn-dag.train manual__2021-11-18T07:15:24.616940+00:00 [queued]>
[2021-11-17 23:15:38,506] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-17 23:15:38,506] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-17 23:15:38,507] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-17 23:15:38,514] {taskinstance.py:1262} INFO - Executing <Task(SageMakerTrainingOperator): train> on 2021-11-18 07:15:24.616940+00:00
[2021-11-17 23:15:38,518] {standard_task_runner.py:52} INFO - Started process 15642 to run task
[2021-11-17 23:15:38,526] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'mwaa-sm-customer-churn-dag', 'train', 'manual__2021-11-18T07:15:24.616940+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/mwaa-customer-churn-dag.py', '--cfg-path', '/var/folders/m8/kcmtvg3x5639v8tv9jcxd6700000gn/T/tmpaiozvh5c', '--error-file', '/var/folders/m8/kcmtvg3x5639v8tv9jcxd6700000gn/T/tmpc_20gw3j']
[2021-11-17 23:15:38,527] {standard_task_runner.py:77} INFO - Job 33: Subtask train
[2021-11-17 23:15:38,578] {logging_mixin.py:109} INFO - Running <TaskInstance: mwaa-sm-customer-churn-dag.train manual__2021-11-18T07:15:24.616940+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-11-17 23:15:38,627] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=mwaa-sm-customer-churn-dag
AIRFLOW_CTX_TASK_ID=train
AIRFLOW_CTX_EXECUTION_DATE=2021-11-18T07:15:24.616940+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-18T07:15:24.616940+00:00
[2021-11-17 23:15:38,628] {sagemaker_base.py:89} INFO - Preprocessing the config and doing required s3_operations
[2021-11-17 23:15:38,629] {sagemaker_base.py:95} INFO - After preprocessing the config is:
 {
    "AlgorithmSpecification": {
        "TrainingImage": "433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1",
        "TrainingInputMode": "File"
    },
    "HyperParameters": {
        "eta": "0.2",
        "gamma": "4",
        "max_depth": "5",
        "min_child_weight": "6",
        "num_round": "100",
        "objective": "binary:logistic",
        "subsample": "0.8"
    },
    "InputDataConfig": [
        {
            "ChannelName": "train",
            "ContentType": "text/csv",
            "DataSource": {
                "S3DataSource": {
                    "S3DataDistributionType": "FullyReplicated",
                    "S3DataType": "S3Prefix",
                    "S3Uri": "s3://shimingr-data/processed/train/"
                }
            }
        },
        {
            "ChannelName": "validation",
            "ContentType": "text/csv",
            "DataSource": {
                "S3DataSource": {
                    "S3DataDistributionType": "FullyReplicated",
                    "S3DataType": "S3Prefix",
                    "S3Uri": "s3://shimingr-data/processed/validation/"
                }
            }
        }
    ],
    "OutputDataConfig": {
        "S3OutputPath": "s3://shimingr-data/model/"
    },
    "ResourceConfig": {
        "InstanceCount": 1,
        "InstanceType": "ml.m5.4xlarge",
        "VolumeSizeInGB": 5
    },
    "RoleArn": "arn:aws:iam::846634201516:role/AmazonMWAA-SageMaker-Role",
    "StoppingCondition": {
        "MaxRuntimeInSeconds": 86400
    },
    "TrainingJobName": "mwaa-sm-training-job-08588a96d07d4ee3b1a0d02ed215cc84"
}
[2021-11-17 23:15:38,630] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=aws_default
[2021-11-17 23:15:38,634] {base_aws.py:177} INFO - Credentials retrieved from login
[2021-11-17 23:15:38,635] {base_aws.py:88} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2021-11-17 23:15:38,635] {base_aws.py:90} INFO - Creating session with aws_access_key_id=AKIA4KH2UWGWPERNDCH5 region_name=us-west-2
[2021-11-17 23:15:38,649] {base_aws.py:168} INFO - role_arn is None
[2021-11-17 23:15:38,656] {logging_mixin.py:109} WARNING - /Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py:494 DeprecationWarning: client_type is deprecated. Set client_type from class attribute.
[2021-11-17 23:15:38,965] {sagemaker_training.py:101} INFO - Creating SageMaker training job mwaa-sm-training-job-08588a96d07d4ee3b1a0d02ed215cc84.
[2021-11-17 23:15:38,966] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=aws_default
[2021-11-17 23:15:38,972] {base_aws.py:177} INFO - Credentials retrieved from login
[2021-11-17 23:15:38,973] {base_aws.py:88} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2021-11-17 23:15:38,973] {base_aws.py:90} INFO - Creating session with aws_access_key_id=AKIA4KH2UWGWPERNDCH5 region_name=us-west-2
[2021-11-17 23:15:38,987] {base_aws.py:168} INFO - role_arn is None
[2021-11-17 23:15:39,839] {sagemaker.py:790} INFO - 2021-11-18 07:15:39 Starting - Starting the training job
[2021-11-17 23:16:39,846] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=aws_default
[2021-11-17 23:16:39,873] {base_aws.py:177} INFO - Credentials retrieved from login
[2021-11-17 23:16:39,874] {base_aws.py:88} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2021-11-17 23:16:39,875] {base_aws.py:90} INFO - Creating session with aws_access_key_id=AKIA4KH2UWGWPERNDCH5 region_name=us-west-2
[2021-11-17 23:16:39,896] {base_aws.py:168} INFO - role_arn is None
[2021-11-17 23:16:40,525] {sagemaker.py:626} INFO - 2021-11-18 07:15:43 Starting - Launching requested ML instances
[2021-11-17 23:17:41,510] {sagemaker.py:626} INFO - 2021-11-18 07:16:44 Starting - Preparing the instances for training
[2021-11-17 23:18:42,017] {sagemaker.py:626} INFO - 2021-11-18 07:18:08 Downloading - Downloading input data
2021-11-18 07:18:08 Failed - Training job failed
[2021-11-17 23:19:42,257] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sagemaker_training.py", line 102, in execute
    response = self.hook.create_training_job(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/sagemaker.py", line 343, in create_training_job
    self.check_training_status_with_log(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/sagemaker.py", line 848, in check_training_status_with_log
    raise AirflowException(f'Error training {job_name}: {status} Reason: {reason}')
airflow.exceptions.AirflowException: Error training mwaa-sm-training-job-08588a96d07d4ee3b1a0d02ed215cc84: Failed Reason: ClientError: Data download failed:403 Forbidden (403): Forbidden
[2021-11-17 23:19:42,275] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=mwaa-sm-customer-churn-dag, task_id=train, execution_date=20211118T071524, start_date=20211118T071538, end_date=20211118T071942
[2021-11-17 23:19:42,291] {standard_task_runner.py:88} ERROR - Failed to execute job 33 for task train
Traceback (most recent call last):
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sagemaker_training.py", line 102, in execute
    response = self.hook.create_training_job(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/sagemaker.py", line 343, in create_training_job
    self.check_training_status_with_log(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/sagemaker.py", line 848, in check_training_status_with_log
    raise AirflowException(f'Error training {job_name}: {status} Reason: {reason}')
airflow.exceptions.AirflowException: Error training mwaa-sm-training-job-08588a96d07d4ee3b1a0d02ed215cc84: Failed Reason: ClientError: Data download failed:403 Forbidden (403): Forbidden
[2021-11-17 23:19:42,316] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-11-17 23:19:42,347] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
