[2021-11-17 22:49:23,347] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: mwaa-sm-customer-churn-dag.train manual__2021-11-18T06:49:14.760349+00:00 [queued]>
[2021-11-17 22:49:23,354] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: mwaa-sm-customer-churn-dag.train manual__2021-11-18T06:49:14.760349+00:00 [queued]>
[2021-11-17 22:49:23,354] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-17 22:49:23,354] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-17 22:49:23,354] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-17 22:49:23,362] {taskinstance.py:1262} INFO - Executing <Task(SageMakerTrainingOperator): train> on 2021-11-18 06:49:14.760349+00:00
[2021-11-17 22:49:23,365] {standard_task_runner.py:52} INFO - Started process 15254 to run task
[2021-11-17 22:49:23,372] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'mwaa-sm-customer-churn-dag', 'train', 'manual__2021-11-18T06:49:14.760349+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/mwaa-customer-churn-dag.py', '--cfg-path', '/var/folders/m8/kcmtvg3x5639v8tv9jcxd6700000gn/T/tmpd2avc1ls', '--error-file', '/var/folders/m8/kcmtvg3x5639v8tv9jcxd6700000gn/T/tmp9wlcujxv']
[2021-11-17 22:49:23,373] {standard_task_runner.py:77} INFO - Job 16: Subtask train
[2021-11-17 22:49:23,425] {logging_mixin.py:109} INFO - Running <TaskInstance: mwaa-sm-customer-churn-dag.train manual__2021-11-18T06:49:14.760349+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-11-17 22:49:23,471] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=mwaa-sm-customer-churn-dag
AIRFLOW_CTX_TASK_ID=train
AIRFLOW_CTX_EXECUTION_DATE=2021-11-18T06:49:14.760349+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-18T06:49:14.760349+00:00
[2021-11-17 22:49:23,472] {sagemaker_base.py:89} INFO - Preprocessing the config and doing required s3_operations
[2021-11-17 22:49:23,473] {sagemaker_base.py:95} INFO - After preprocessing the config is:
 {
    "AlgorithmSpecification": {
        "TrainingImage": "433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1",
        "TrainingInputMode": "File"
    },
    "HyperParameters": {
        "eta": "0.2",
        "gamma": "4",
        "max_depth": "5",
        "min_child_weight": "6",
        "num_round": "100",
        "objective": "binary:logistic",
        "subsample": "0.8"
    },
    "InputDataConfig": [
        {
            "ChannelName": "train",
            "ContentType": "text/csv",
            "DataSource": {
                "S3DataSource": {
                    "S3DataDistributionType": "FullyReplicated",
                    "S3DataType": "S3Prefix",
                    "S3Uri": "s3://shimingr-data/processed/train/"
                }
            }
        },
        {
            "ChannelName": "validation",
            "ContentType": "text/csv",
            "DataSource": {
                "S3DataSource": {
                    "S3DataDistributionType": "FullyReplicated",
                    "S3DataType": "S3Prefix",
                    "S3Uri": "s3://shimingr-data/processed/validation/"
                }
            }
        }
    ],
    "OutputDataConfig": {
        "S3OutputPath": "s3://shimingr-data/model/"
    },
    "ResourceConfig": {
        "InstanceCount": 1,
        "InstanceType": "ml.m5.4xlarge",
        "VolumeSizeInGB": 5
    },
    "RoleArn": "arn:aws:iam::846634201516:role/AmazonMWAA-SageMaker-Role",
    "StoppingCondition": {
        "MaxRuntimeInSeconds": 86400
    },
    "TrainingJobName": "mwaa-sm-training-job-72a2ee337dc14806a5ba46a2b2fd66f5"
}
[2021-11-17 22:49:23,474] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=airflow-sagemaker
[2021-11-17 22:49:23,477] {base_aws.py:424} WARNING - Unable to use Airflow Connection for credentials.
[2021-11-17 22:49:23,478] {base_aws.py:425} INFO - Fallback on boto3 credential strategy
[2021-11-17 22:49:23,478] {base_aws.py:428} INFO - Creating session using boto3 credential strategy region_name=None
[2021-11-17 22:49:23,496] {logging_mixin.py:109} WARNING - /Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py:494 DeprecationWarning: client_type is deprecated. Set client_type from class attribute.
[2021-11-17 22:49:23,500] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-11-17 22:49:23,768] {sagemaker_training.py:101} INFO - Creating SageMaker training job mwaa-sm-training-job-72a2ee337dc14806a5ba46a2b2fd66f5.
[2021-11-17 22:49:23,769] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=airflow-sagemaker
[2021-11-17 22:49:23,772] {base_aws.py:424} WARNING - Unable to use Airflow Connection for credentials.
[2021-11-17 22:49:23,773] {base_aws.py:425} INFO - Fallback on boto3 credential strategy
[2021-11-17 22:49:23,773] {base_aws.py:428} INFO - Creating session using boto3 credential strategy region_name=None
[2021-11-17 22:49:23,787] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-11-17 22:49:24,636] {sagemaker.py:790} INFO - 2021-11-18 06:49:24 Starting - Starting the training job
[2021-11-17 22:50:24,639] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=airflow-sagemaker
[2021-11-17 22:50:24,650] {base_aws.py:424} WARNING - Unable to use Airflow Connection for credentials.
[2021-11-17 22:50:24,650] {base_aws.py:425} INFO - Fallback on boto3 credential strategy
[2021-11-17 22:50:24,651] {base_aws.py:428} INFO - Creating session using boto3 credential strategy region_name=None
[2021-11-17 22:50:24,674] {credentials.py:1222} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2021-11-17 22:50:25,221] {sagemaker.py:626} INFO - 2021-11-18 06:50:21 Starting - Preparing the instances for training
[2021-11-17 22:52:26,180] {sagemaker.py:626} INFO - 2021-11-18 06:52:05 Downloading - Downloading input data
2021-11-18 06:52:05 Failed - Training job failed
[2021-11-17 22:52:35,052] {local_task_job.py:211} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2021-11-17 22:52:35,069] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 15254
[2021-11-17 22:52:35,070] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-17 22:52:35,124] {process_utils.py:66} INFO - Process psutil.Process(pid=15254, status='terminated', exitcode=0, started='22:49:23') (15254) terminated with exit code 0
