[2021-11-17 23:34:35,523] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: mwaa-sm-customer-churn-dag.endpoint-deploy manual__2021-11-18T07:29:59.459300+00:00 [queued]>
[2021-11-17 23:34:35,530] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: mwaa-sm-customer-churn-dag.endpoint-deploy manual__2021-11-18T07:29:59.459300+00:00 [queued]>
[2021-11-17 23:34:35,531] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-17 23:34:35,531] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-17 23:34:35,531] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-17 23:34:35,544] {taskinstance.py:1262} INFO - Executing <Task(SageMakerEndpointOperator): endpoint-deploy> on 2021-11-18 07:29:59.459300+00:00
[2021-11-17 23:34:35,548] {standard_task_runner.py:52} INFO - Started process 15812 to run task
[2021-11-17 23:34:35,556] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'mwaa-sm-customer-churn-dag', 'endpoint-deploy', 'manual__2021-11-18T07:29:59.459300+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/mwaa-customer-churn-dag.py', '--cfg-path', '/var/folders/m8/kcmtvg3x5639v8tv9jcxd6700000gn/T/tmpjib5gkjl', '--error-file', '/var/folders/m8/kcmtvg3x5639v8tv9jcxd6700000gn/T/tmpvxh9ligr']
[2021-11-17 23:34:35,558] {standard_task_runner.py:77} INFO - Job 41: Subtask endpoint-deploy
[2021-11-17 23:34:35,609] {logging_mixin.py:109} INFO - Running <TaskInstance: mwaa-sm-customer-churn-dag.endpoint-deploy manual__2021-11-18T07:29:59.459300+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-17 23:34:35,686] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=mwaa-sm-customer-churn-dag
AIRFLOW_CTX_TASK_ID=endpoint-deploy
AIRFLOW_CTX_EXECUTION_DATE=2021-11-18T07:29:59.459300+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-18T07:29:59.459300+00:00
[2021-11-17 23:34:35,687] {sagemaker_base.py:89} INFO - Preprocessing the config and doing required s3_operations
[2021-11-17 23:34:35,689] {sagemaker_base.py:95} INFO - After preprocessing the config is:
 {
    "Endpoint": {
        "EndpointConfigName": "mwaa-sm-customer-churn-model-27d3a1452377414b81b8a5fd43763b4d",
        "EndpointName": "mwaa-sm-endpoint-27d3a1452377414b81b8a5fd43763b4d"
    },
    "EndpointConfig": {
        "EndpointConfigName": "mwaa-sm-customer-churn-model-27d3a1452377414b81b8a5fd43763b4d",
        "ProductionVariants": [
            {
                "InitialInstanceCount": 1,
                "InitialVariantWeight": 1,
                "InstanceType": "ml.m4.xlarge",
                "ModelName": "mwaa-sm-customer-churn-model-27d3a1452377414b81b8a5fd43763b4d",
                "VariantName": "AllTraffic"
            }
        ]
    },
    "Model": {
        "ExecutionRoleArn": "arn:aws:iam::846634201516:role/AmazonMWAA-SageMaker-Role",
        "ModelName": "mwaa-sm-customer-churn-model-27d3a1452377414b81b8a5fd43763b4d",
        "PrimaryContainer": {
            "Environment": {},
            "Image": "433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1",
            "ModelDataUrl": "s3://shimingr-data/model/mwaa-sm-training-job-18085841a5824d76920212b59e88a5d1/output/model.tar.gz"
        }
    }
}
[2021-11-17 23:34:35,690] {sagemaker_endpoint.py:115} INFO - Creating SageMaker model mwaa-sm-customer-churn-model-27d3a1452377414b81b8a5fd43763b4d.
[2021-11-17 23:34:35,691] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=aws_default
[2021-11-17 23:34:35,696] {base_aws.py:177} INFO - Credentials retrieved from login
[2021-11-17 23:34:35,697] {base_aws.py:88} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2021-11-17 23:34:35,698] {base_aws.py:90} INFO - Creating session with aws_access_key_id=AKIA4KH2UWGWPERNDCH5 region_name=us-west-2
[2021-11-17 23:34:35,716] {base_aws.py:168} INFO - role_arn is None
[2021-11-17 23:34:35,722] {logging_mixin.py:109} WARNING - /Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py:494 DeprecationWarning: client_type is deprecated. Set client_type from class attribute.
[2021-11-17 23:34:36,355] {sagemaker_endpoint.py:119} INFO - Creating endpoint config mwaa-sm-customer-churn-model-27d3a1452377414b81b8a5fd43763b4d.
[2021-11-17 23:34:36,460] {sagemaker_endpoint.py:131} INFO - Creating SageMaker endpoint mwaa-sm-endpoint-27d3a1452377414b81b8a5fd43763b4d.
[2021-11-17 23:35:37,226] {sagemaker.py:737} INFO - Job still running for 60 seconds... current status is Creating
[2021-11-17 23:36:01,301] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa does not match this instance's hostname 1.0.0.127.in-addr.arpa
[2021-11-17 23:36:01,313] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 15812
[2021-11-17 23:36:01,314] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-17 23:36:01,319] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sagemaker_endpoint.py", line 133, in execute
    response = sagemaker_operation(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/sagemaker.py", line 519, in create_endpoint
    self.check_status(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/sagemaker.py", line 731, in check_status
    time.sleep(check_interval)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-17 23:36:01,333] {taskinstance.py:1270} INFO - Marking task as FAILED. dag_id=mwaa-sm-customer-churn-dag, task_id=endpoint-deploy, execution_date=20211118T072959, start_date=20211118T073435, end_date=20211118T073601
[2021-11-17 23:36:01,343] {standard_task_runner.py:88} ERROR - Failed to execute job 41 for task endpoint-deploy
Traceback (most recent call last):
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sagemaker_endpoint.py", line 133, in execute
    response = sagemaker_operation(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/sagemaker.py", line 519, in create_endpoint
    self.check_status(
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/sagemaker.py", line 731, in check_status
    time.sleep(check_interval)
  File "/Users/shimingr/mlops/airflow/venv2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-11-17 23:36:01,376] {process_utils.py:66} INFO - Process psutil.Process(pid=15812, status='terminated', exitcode=1, started='23:34:35') (15812) terminated with exit code 1
